// <auto-generated />
using System;
using LifeLineApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeLineApi.Migrations
{
    [DbContext(typeof(LifeLinedbContext))]
    [Migration("20231112105527_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LifeLineApi.Models.ApplicationAdmin", b =>
                {
                    b.Property<int>("AaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AaId"));

                    b.Property<string>("AaEmail")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("AA_Email");

                    b.Property<string>("AaPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AA_Password");

                    b.Property<string>("AaUserName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("AA_UserName");

                    b.HasKey("AaId")
                        .HasName("PK__Applicat__509C98E66D8C254A");

                    b.ToTable("Application_Admin", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.Appointment", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("A_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AId"));

                    b.Property<int?>("ADId")
                        .HasColumnType("int")
                        .HasColumnName("A_D_ID");

                    b.Property<DateTime?>("ADate")
                        .HasColumnType("date")
                        .HasColumnName("A_Date");

                    b.Property<string>("AEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("A_Email");

                    b.Property<int?>("AHId")
                        .HasColumnType("int")
                        .HasColumnName("A_H_ID");

                    b.Property<string>("AMobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("A_Mobile");

                    b.Property<DateTime?>("APatientDob")
                        .HasColumnType("date")
                        .HasColumnName("A_PatientDOB");

                    b.Property<string>("APatientName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("A_PatientName");

                    b.Property<string>("AReason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("A_Reason");

                    b.Property<TimeSpan?>("ATime")
                        .HasColumnType("time")
                        .HasColumnName("A_Time");

                    b.Property<string>("AType")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("A_Type");

                    b.HasKey("AId")
                        .HasName("PK__Appointm__71AC6D412B7481FC");

                    b.HasIndex("ADId");

                    b.HasIndex("AHId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LifeLineApi.Models.BloodAvailability", b =>
                {
                    b.Property<int>("BaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BA_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaId"));

                    b.Property<string>("BaBloodGroup")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("BA_BloodGroup");

                    b.Property<int?>("BaBottlesAvailable")
                        .HasColumnType("int")
                        .HasColumnName("BA_BottlesAvailable");

                    b.Property<DateTime?>("BaDate")
                        .HasColumnType("date")
                        .HasColumnName("BA_Date");

                    b.Property<int?>("BaHId")
                        .HasColumnType("int")
                        .HasColumnName("BA_H_ID");

                    b.Property<TimeSpan?>("BaTime")
                        .HasColumnType("time")
                        .HasColumnName("BA_Time");

                    b.HasKey("BaId")
                        .HasName("PK__Blood_Av__6DFCF7B82E636F43");

                    b.HasIndex("BaHId");

                    b.ToTable("Blood_Availability", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.Doctor", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("D_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DId"));

                    b.Property<string>("DAvailablityStatus")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("D_AvailablityStatus");

                    b.Property<string>("DEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("D_Email");

                    b.Property<string>("DField")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("D_Field");

                    b.Property<int?>("DHId")
                        .HasColumnType("int")
                        .HasColumnName("D_H_ID");

                    b.Property<string>("DImage")
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("d_image");

                    b.Property<string>("DMobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("D_Mobile");

                    b.Property<string>("DName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("D_Name");

                    b.Property<string>("DPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("D_Password");

                    b.HasKey("DId")
                        .HasName("PK__Doctors__76B8FF7DAC4F92E9");

                    b.HasIndex("DHId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("LifeLineApi.Models.DoctorPrescription", b =>
                {
                    b.Property<int>("DpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DpId"));

                    b.Property<int?>("DpDId")
                        .HasColumnType("int")
                        .HasColumnName("DP_D_ID");

                    b.Property<DateTime?>("DpDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DP_Date");

                    b.Property<string>("DpDisease")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DP_Disease");

                    b.Property<int?>("DpPId")
                        .HasColumnType("int")
                        .HasColumnName("DP_P_ID");

                    b.HasKey("DpId")
                        .HasName("PK__Doctor_P__7E732EA09FF169F0");

                    b.HasIndex("DpDId");

                    b.HasIndex("DpPId");

                    b.ToTable("Doctor_Prescription", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.EmergencyContact", b =>
                {
                    b.Property<int>("EcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EcId"));

                    b.Property<int?>("EcHId")
                        .HasColumnType("int")
                        .HasColumnName("EC_H_ID");

                    b.Property<string>("EcNumber1")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("EC_Number1");

                    b.Property<string>("EcNumber2")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("EC_Number2");

                    b.HasKey("EcId")
                        .HasName("PK__Emergenc__46237E5951031F2D");

                    b.HasIndex("EcHId");

                    b.ToTable("Emergency_Contact", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.Feedback", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("F_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FId"));

                    b.Property<string>("FComments")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("F_Comments");

                    b.Property<int?>("FDId")
                        .HasColumnType("int")
                        .HasColumnName("F_D_ID");

                    b.Property<int?>("FPId")
                        .HasColumnType("int")
                        .HasColumnName("F_P_ID");

                    b.Property<int?>("FRating")
                        .HasColumnType("int")
                        .HasColumnName("F_Rating");

                    b.HasKey("FId")
                        .HasName("PK__Feedback__2C6EC7C3D9F307C6");

                    b.HasIndex("FDId");

                    b.HasIndex("FPId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.HEmployee", b =>
                {
                    b.Property<int>("HeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeId"));

                    b.Property<string>("HeEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HE_Email");

                    b.Property<int?>("HeHId")
                        .HasColumnType("int")
                        .HasColumnName("HE_H_ID");

                    b.Property<string>("HeName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("HE_Name");

                    b.Property<string>("HePassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HE_Password");

                    b.Property<string>("HeRole")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("HE_Role");

                    b.HasKey("HeId")
                        .HasName("PK__H_Employ__692EA79EF70025B5");

                    b.HasIndex("HeHId");

                    b.ToTable("H_Employee", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.Hospital", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HId"));

                    b.Property<string>("HAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("H_Address");

                    b.Property<string>("HEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("H_Email");

                    b.Property<string>("HName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("H_Name");

                    b.Property<string>("HPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("H_Password");

                    b.Property<double?>("HlLatitude")
                        .HasColumnType("float")
                        .HasColumnName("HL_Latitude");

                    b.Property<double?>("HlLongitude")
                        .HasColumnType("float")
                        .HasColumnName("HL_Longitude");

                    b.HasKey("HId")
                        .HasName("PK__Hospital__61F3893D78B274C2");

                    b.ToTable("Hospital", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.MedicalPortfolio", b =>
                {
                    b.Property<int>("MpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MpId"));

                    b.Property<int?>("MpDpId")
                        .HasColumnType("int")
                        .HasColumnName("MP_DP_ID");

                    b.Property<int?>("MpPId")
                        .HasColumnType("int")
                        .HasColumnName("MP_P_ID");

                    b.Property<int?>("MpPmId")
                        .HasColumnType("int")
                        .HasColumnName("MP_PM_ID");

                    b.HasKey("MpId")
                        .HasName("PK__Medical___D12FC71573D6D922");

                    b.HasIndex("MpDpId");

                    b.HasIndex("MpPId");

                    b.HasIndex("MpPmId");

                    b.ToTable("Medical_Portfolio", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.Patient", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("P_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<string>("PAStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("P_A_Status");

                    b.Property<int?>("PDId")
                        .HasColumnType("int")
                        .HasColumnName("P_D_ID");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("date")
                        .HasColumnName("P_Date");

                    b.Property<DateTime?>("PDob")
                        .HasColumnType("date")
                        .HasColumnName("P_DOB");

                    b.Property<string>("PEmail")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("P_Email");

                    b.Property<string>("PMobile")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("P_Mobile");

                    b.Property<string>("PName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("P_Name");

                    b.Property<string>("PPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("P_Password");

                    b.Property<string>("PReason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("P_Reason");

                    b.Property<TimeSpan?>("PTime")
                        .HasColumnType("time")
                        .HasColumnName("P_Time");

                    b.HasKey("PId")
                        .HasName("PK__Patients__A3420A77592C4340");

                    b.HasIndex("PDId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("LifeLineApi.Models.PrescriptionMedication", b =>
                {
                    b.Property<int>("PmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PmId"));

                    b.Property<string>("PmDosage")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PM_Dosage");

                    b.Property<int?>("PmDpId")
                        .HasColumnType("int")
                        .HasColumnName("PM_DP_ID");

                    b.Property<DateTime?>("PmEndDate")
                        .HasColumnType("date")
                        .HasColumnName("PM_EndDate");

                    b.Property<string>("PmMedicine")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PM_Medicine");

                    b.Property<TimeSpan?>("PmScheduleTime")
                        .HasColumnType("time")
                        .HasColumnName("PM_ScheduleTime");

                    b.Property<DateTime?>("PmStartDate")
                        .HasColumnType("date")
                        .HasColumnName("PM_StartDate");

                    b.HasKey("PmId")
                        .HasName("PK__Prescrip__8E8EC70B6630E1AA");

                    b.HasIndex("PmDpId");

                    b.ToTable("Prescription_Medications", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.VideoConsultation", b =>
                {
                    b.Property<int>("VcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VcId"));

                    b.Property<int?>("VcDId")
                        .HasColumnType("int")
                        .HasColumnName("VC_D_ID");

                    b.Property<DateTime?>("VcDate")
                        .HasColumnType("date")
                        .HasColumnName("VC_Date");

                    b.Property<int?>("VcPId")
                        .HasColumnType("int")
                        .HasColumnName("VC_P_ID");

                    b.Property<TimeSpan?>("VcTime")
                        .HasColumnType("time")
                        .HasColumnName("VC_Time");

                    b.HasKey("VcId")
                        .HasName("PK__Video_Co__FFB4AD255FFE2FE3");

                    b.HasIndex("VcDId");

                    b.HasIndex("VcPId");

                    b.ToTable("Video_Consultation", (string)null);
                });

            modelBuilder.Entity("LifeLineApi.Models.Appointment", b =>
                {
                    b.HasOne("LifeLineApi.Models.Doctor", "AD")
                        .WithMany("Appointments")
                        .HasForeignKey("ADId")
                        .HasConstraintName("FK__Appointme__A_D_I__5165187F");

                    b.HasOne("LifeLineApi.Models.Hospital", "AH")
                        .WithMany("Appointments")
                        .HasForeignKey("AHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Appointme__A_H_I__5070F446");

                    b.Navigation("AD");

                    b.Navigation("AH");
                });

            modelBuilder.Entity("LifeLineApi.Models.BloodAvailability", b =>
                {
                    b.HasOne("LifeLineApi.Models.Hospital", "BaH")
                        .WithMany("BloodAvailabilities")
                        .HasForeignKey("BaHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Blood_Ava__BA_H___59FA5E80");

                    b.Navigation("BaH");
                });

            modelBuilder.Entity("LifeLineApi.Models.Doctor", b =>
                {
                    b.HasOne("LifeLineApi.Models.Hospital", "DH")
                        .WithMany("Doctors")
                        .HasForeignKey("DHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Doctors__D_H_ID__4D94879B");

                    b.Navigation("DH");
                });

            modelBuilder.Entity("LifeLineApi.Models.DoctorPrescription", b =>
                {
                    b.HasOne("LifeLineApi.Models.Doctor", "DpD")
                        .WithMany("DoctorPrescriptions")
                        .HasForeignKey("DpDId")
                        .HasConstraintName("FK__Doctor_Pr__DP_D___5CD6CB2B");

                    b.HasOne("LifeLineApi.Models.Patient", "DpP")
                        .WithMany("DoctorPrescriptions")
                        .HasForeignKey("DpPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Doctor_Pr__DP_P___5DCAEF64");

                    b.Navigation("DpD");

                    b.Navigation("DpP");
                });

            modelBuilder.Entity("LifeLineApi.Models.EmergencyContact", b =>
                {
                    b.HasOne("LifeLineApi.Models.Hospital", "EcH")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("EcHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emergency__EC_H___6B24EA82");

                    b.Navigation("EcH");
                });

            modelBuilder.Entity("LifeLineApi.Models.Feedback", b =>
                {
                    b.HasOne("LifeLineApi.Models.Doctor", "FD")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Feedback__F_D_ID__60A75C0F");

                    b.HasOne("LifeLineApi.Models.Patient", "FP")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FPId")
                        .HasConstraintName("FK__Feedback__F_P_ID__619B8048");

                    b.Navigation("FD");

                    b.Navigation("FP");
                });

            modelBuilder.Entity("LifeLineApi.Models.HEmployee", b =>
                {
                    b.HasOne("LifeLineApi.Models.Hospital", "HeH")
                        .WithMany("HEmployees")
                        .HasForeignKey("HeHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__H_Employe__HE_H___571DF1D5");

                    b.Navigation("HeH");
                });

            modelBuilder.Entity("LifeLineApi.Models.MedicalPortfolio", b =>
                {
                    b.HasOne("LifeLineApi.Models.DoctorPrescription", "MpDp")
                        .WithMany("MedicalPortfolios")
                        .HasForeignKey("MpDpId")
                        .HasConstraintName("FK__Medical_P__MP_DP__6E01572D");

                    b.HasOne("LifeLineApi.Models.Patient", "MpP")
                        .WithMany("MedicalPortfolios")
                        .HasForeignKey("MpPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Medical_P__MP_P___6EF57B66");

                    b.HasOne("LifeLineApi.Models.PrescriptionMedication", "MpPm")
                        .WithMany("MedicalPortfolios")
                        .HasForeignKey("MpPmId")
                        .HasConstraintName("FK__Medical_P__MP_PM__6FE99F9F");

                    b.Navigation("MpDp");

                    b.Navigation("MpP");

                    b.Navigation("MpPm");
                });

            modelBuilder.Entity("LifeLineApi.Models.Patient", b =>
                {
                    b.HasOne("LifeLineApi.Models.Doctor", "PD")
                        .WithMany("Patients")
                        .HasForeignKey("PDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Patients__P_D_ID__5441852A");

                    b.Navigation("PD");
                });

            modelBuilder.Entity("LifeLineApi.Models.PrescriptionMedication", b =>
                {
                    b.HasOne("LifeLineApi.Models.DoctorPrescription", "PmDp")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("PmDpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Prescript__PM_DP__68487DD7");

                    b.Navigation("PmDp");
                });

            modelBuilder.Entity("LifeLineApi.Models.VideoConsultation", b =>
                {
                    b.HasOne("LifeLineApi.Models.Doctor", "VcD")
                        .WithMany("VideoConsultations")
                        .HasForeignKey("VcDId")
                        .HasConstraintName("FK__Video_Con__VC_D___6477ECF3");

                    b.HasOne("LifeLineApi.Models.Patient", "VcP")
                        .WithMany("VideoConsultations")
                        .HasForeignKey("VcPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Video_Con__VC_P___656C112C");

                    b.Navigation("VcD");

                    b.Navigation("VcP");
                });

            modelBuilder.Entity("LifeLineApi.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorPrescriptions");

                    b.Navigation("Feedbacks");

                    b.Navigation("Patients");

                    b.Navigation("VideoConsultations");
                });

            modelBuilder.Entity("LifeLineApi.Models.DoctorPrescription", b =>
                {
                    b.Navigation("MedicalPortfolios");

                    b.Navigation("PrescriptionMedications");
                });

            modelBuilder.Entity("LifeLineApi.Models.Hospital", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BloodAvailabilities");

                    b.Navigation("Doctors");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("HEmployees");
                });

            modelBuilder.Entity("LifeLineApi.Models.Patient", b =>
                {
                    b.Navigation("DoctorPrescriptions");

                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalPortfolios");

                    b.Navigation("VideoConsultations");
                });

            modelBuilder.Entity("LifeLineApi.Models.PrescriptionMedication", b =>
                {
                    b.Navigation("MedicalPortfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
